feat: linux support

diff --git a/AAPFunction b/AAPFunction
--- a/AAPFunction
+++ b/AAPFunction
@@ -20,17 +20,17 @@ get_device_boot() { # 未指定boot路径时从设备boot分区获取boot镜像
 
 get_tools() { # 从GitHub下载工具
 	cd ${WORKDIR} || exit 1
-	echo "${BLUE}I: Downloading kptools-android...${RESET}"
+	echo "${BLUE}I: Downloading kptools-${OS}...${RESET}"
 	if [[ -n "${KPTOOLVER}" ]]; then
 		echo "${BLUE}I: Use the specified version: ${KPTOOLVER}${RESET}"
 	else
 		echo "${BLUE}I: Use the latest kptools.${RESET}"
 	fi
 	if [[ -n "${KPTOOLVER}" ]]; then
-		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/download/${KPTOOLVER}/kptools-android"
+		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/download/${KPTOOLVER}/kptools-${OS}"
 		EXITSTATUS=$?
 	else
-		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/latest/download/kptools-android"
+		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/latest/download/kptools-${OS}"
 		EXITSTATUS=$?
 	fi
 	if [[ $EXITSTATUS != 0 ]]; then
@@ -38,7 +38,7 @@ get_tools() { # 从GitHub下载工具
 		echo "Please check your internet connection."
 		exit 1
 	fi
-	chmod +x kptools-android
+	chmod +x kptools-${OS}
 	echo "${GREEN}I: Done.${RESET}"
 	echo "${BLUE}I: Downloading kpimg-android...${RESET}"
 	if [[ -n "${KPTOOLVER}" ]]; then
@@ -100,7 +100,7 @@ patch_boot() { # 修补boot镜像
 	#   -V, --extra-event EVENT          Set trigger event of previous extra item.
 	#   -A, --extra-args ARGS            Set arguments of previous extra item.
 	#   -D, --extra-detach               Detach previous extra item from patches.
-	./kptools-android --unpatch --image kernel --out kernel || EXITSTATUS=$?
+	./kptools-${OS} --unpatch --image kernel --out kernel || EXITSTATUS=$?
 	if [[ ${EXITSTATUS} != 0 ]]; then
 		echo "${YELLOW}I: Maybe you are using stock boot image?${RESET}"
 		echo "${YELLOW}W: Now skipping unpatching...${RESET}"
@@ -108,7 +108,7 @@ patch_boot() { # 修补boot镜像
 		echo "${GREEN}I: Done.${RESET}"
 	fi
 	echo "${BLUE}I: Patching image...Current Superkey: ${SUPERKEY}${RESET}"
-	./kptools-android --patch --kpimg kpimg-android --skey "${SUPERKEY}" --image kernel --out kernel
+	./kptools-${OS} --patch --kpimg kpimg-android --skey "${SUPERKEY}" --image kernel --out kernel
 	EXITSTATUS=$?
 	if [[ ${EXITSTATUS} != 0 ]]; then
 		echo "${RED}E: PATCH FAILED!${RESET}"
@@ -126,25 +126,29 @@ patch_boot() { # 修补boot镜像
 }
 
 flash_boot() { # 刷入boot镜像
-	echo "${BLUE}I: Flashing boot image...${RESET}"
-	dd if=${WORKDIR}/new-boot.img of=/dev/block/by-name/boot${BOOTSUFFIX}
-	EXITSTATUS=$?
-	if [[ ${EXITSTATUS} != 0 ]]; then
-		echo "${RED}E: WARNING!!! IMAGE FLASH FAILED${RESET}"
-		echo "${YELLOW}I: Now trying to restore...${RESET}"
-		dd if=${WORKDIR}/boot${BOOTSUFFIX}.img of=/dev/block/by-name/boot${BOOTSUFFIX}
+	if [[ "${OS}" != "linux" ]]; then
+		echo "${BLUE}I: Flashing boot image...${RESET}"
+		dd if=${WORKDIR}/new-boot.img of=/dev/block/by-name/boot${BOOTSUFFIX}
 		EXITSTATUS=$?
 		if [[ ${EXITSTATUS} != 0 ]]; then
-			echo "${RED}E: WARNING!!! RESTORE FAILED!!!"
-			echo "Even I can't help you now. You can try to restore boot manually.${RESET}"
-			exit 1
+			echo "${RED}E: WARNING!!! IMAGE FLASH FAILED${RESET}"
+			echo "${YELLOW}I: Now trying to restore...${RESET}"
+			dd if=${WORKDIR}/boot${BOOTSUFFIX}.img of=/dev/block/by-name/boot${BOOTSUFFIX}
+			EXITSTATUS=$?
+			if [[ ${EXITSTATUS} != 0 ]]; then
+				echo "${RED}E: WARNING!!! RESTORE FAILED!!!"
+				echo "Even I can't help you now. You can try to restore boot manually.${RESET}"
+				exit 1
+			fi
+			echo "${YELLOW}I: Restore Sucessfully.${RESET}"
 		fi
-		echo "${YELLOW}I: Restore Sucessfully.${RESET}"
+		echo "${GREEN}I: Flash done.${RESET}"
+		echo "${BLUE}I: Cleaning temporary files...${RESET}"
+		rm -rf ${WORKDIR}
+		echo "${GREEN}I: Done.${RESET}"
+	else
+		echo "${RED}E: You are trying to change this script. Linux does not require a flashing step. This is the second level of warning.${RESET}"
 	fi
-	echo "${GREEN}I: Flash done.${RESET}"
-	echo "${BLUE}I: Cleaning temporary files...${RESET}"
-	rm -rf ${WORKDIR}
-	echo "${GREEN}I: Done.${RESET}"
 }
 
 print_superkey() { # 打印 SUPERKEY
