Major Upd: bump version && drop old version

diff --git a/AAPFunction b/AAPFunction
--- a/AAPFunction
+++ b/AAPFunction
@@ -1,30 +1,30 @@
 #!/bin/env bash
-#by nya
-#2024-02-04
+#by Akina
+#2024-06-03
 
 get_device_boot() { # 未指定boot路径时从设备boot分区获取boot镜像
-	echo "${BLUE}I: Getting boot image...${RESET}"
+	log_info "Getting boot image..."
 	if [[ -z "${BOOTPATH}" ]]; then
-		echo "${BLUE}I: Current boot: ${BOOTSUFFIX}(If empty: A-Only devices)${RESET}"
+		log_info "Current boot: ${BOOTSUFFIX}(If empty: A-Only devices)"
 		dd if=${BYNAMEPATH}/boot${BOOTSUFFIX} of=${WORKDIR}/boot${BOOTSUFFIX}.img
 		EXITSTATUS=$?
 		if [[ $EXITSTATUS != 0 ]]; then
-			echo "${RED}E: GET BOOT IMAGE FAILED${RESET}"
+			log_err "GET BOOT IMAGE FAILED!"
 			exit 1
 		fi
 	else
 		cp ${BOOTPATH} ${WORKDIR}/boot${BOOTSUFFIX}.img
 	fi
-	echo "${GREEN}I: Done.${RESET}"
+	log_info "Done."
 }
 
 get_tools() { # 从GitHub下载工具
 	cd ${WORKDIR} || exit 1
-	echo "${BLUE}I: Downloading kptools-${OS}...${RESET}"
+	log_info "Downloading kptools-${OS}..."
 	if [[ -n "${KPTOOLVER}" ]]; then
-		echo "${BLUE}I: Use the specified version: ${KPTOOLVER}${RESET}"
+		log_info "Use the specified version: ${KPTOOLVER}"
 	else
-		echo "${BLUE}I: Use the latest kptools.${RESET}"
+		log_info "Use the latest kptools."
 	fi
 	if [[ -n "${KPTOOLVER}" ]]; then
 		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/download/${KPTOOLVER}/kptools-${OS}"
@@ -34,13 +34,13 @@ get_tools() { # 从GitHub下载工具
 		EXITSTATUS=$?
 	fi
 	if [[ $EXITSTATUS != 0 ]]; then
-		echo "${RED}E: DOWNLOAD FAILED${RESET}"
-		echo "Please check your internet connection."
+		log_err "DOWNLOAD FAILED!"
+		log_err "Please check your internet connection."
 		exit 1
 	fi
 	chmod +x kptools-${OS}
-	echo "${GREEN}I: Done.${RESET}"
-	echo "${BLUE}I: Downloading kpimg-android...${RESET}"
+	log_info "Done."
+	log_info "Downloading kpimg-android..."
 	if [[ -n "${KPTOOLVER}" ]]; then
 		curl -LO --progress-bar "https://github.com/bmax121/KernelPatch/releases/download/${KPTOOLVER}/kpimg-android"
 		EXITSTATUS=$?
@@ -49,85 +49,86 @@ get_tools() { # 从GitHub下载工具
 		EXITSTATUS=$?
 	fi
 	if [[ $EXITSTATUS != 0 ]]; then
-		echo "${RED}E: DOWNLOAD FAILED${RESET}"
-		echo "Please check your internet connection."
+		log_err "DOWNLOAD FAILED!"
+		log_err "Please check your internet connection."
 		exit 1
 	fi
-	echo "${GREEN}I: Done.${RESET}"
-	echo "${BLUE}I: Downloading magiskboot...${RESET}"
-	curl -LO --progress-bar "https://raw.githubusercontent.com/nya-main/APatchAutoPatchTool/main/bin/magiskboot"
+	log_info "Done."
+	log_info "Downloading magiskboot..."
+	curl -LO --progress-bar "https://raw.githubusercontent.com/AkinaAcct/APatchTool/main/bin/magiskboot"
 	EXITSTATUS=$?
 	if [[ $EXITSTATUS != 0 ]]; then
-		echo "${RED}E: DOWNLOAD FAILED${RESET}"
-		echo "Please check your internet connection."
+		log_err "DOWNLOAD FAILED!"
+		log_err "Please check your internet connection."
 		exit 1
 	fi
 	chmod +x magiskboot
-	echo "${GREEN}I: Done.${RESET}"
+	log_info "Done."
 }
 
 patch_boot() { # 修补boot镜像
-	echo "${BLUE}I: Unpacking image...${RESET}"
+	log_info "Unpacking image..."
 	./magiskboot unpack boot${BOOTSUFFIX}.img
 	EXITSTATUS=$?
 	if [[ $EXITSTATUS != 0 ]]; then
-		echo "${RED}E: UNPACK BOOT IMAGE FAILED!${RESET}"
+		log_err "UNPACK BOOT IMAGE FAILED!"
 		exit 1
 	fi
-	echo "${GREEN}I: Done.${RESET}"
-	echo "${BLUE}I: Unpatching current image...${RESET}"
-	./kptools-${OS} --unpatch --image kernel --out kernel ${EXTRAARGS} || EXITSTATUS=$? 
+	log_info "Done."
+	log_info "Unpatching current image..."
+	./kptools-${OS} --unpatch --image kernel --out kernel || EXITSTATUS=$?
 	if [[ ${EXITSTATUS} != 0 ]]; then
-		echo "${YELLOW}I: Maybe you are using stock boot image?${RESET}"
-		echo "${YELLOW}W: Now skipping unpatching...${RESET}"
+		log_warn "Unpatch failed. Maybe you are using a unpatched boot image?"
+		log_warn "Now skipping unpatching..."
 	else
-		echo "${GREEN}I: Done.${RESET}"
+		log_warn "Done."
 	fi
-	echo "${BLUE}I: Patching image...Current Superkey: ${SUPERKEY}${RESET}"
-	./kptools-${OS} --patch --kpimg kpimg-android --skey "${SUPERKEY}" --image kernel --out kernel
+	log_info "Patching image...Current Superkey: ${SUPERKEY}"
+	./kptools-${OS} --patch --kpimg kpimg-android --skey "${SUPERKEY}" --image kernel --out kernel ${EXTRAARGS}
 	EXITSTATUS=$?
 	if [[ ${EXITSTATUS} != 0 ]]; then
-		echo "${RED}E: PATCH FAILED!${RESET}"
+		log_err "PATCH FAILED!"
 		exit 1
 	fi
-	echo "${GREEN}I: Done${RESET}"
-	echo "${BLUE}I: Repacking...${RESET}"
+	log_info "Done."
+	log_info "Repacking..."
 	./magiskboot repack boot${BOOTSUFFIX}.img
 	EXITSTATUS=$?
 	if [[ $EXITSTATUS != 0 ]]; then
-		echo "${RED}E: REPACK FAILED!${RESET}"
+		log_err "REPACK FAILED!"
 		exit 1
 	fi
-	echo "${GREEN}I: Done.${RESET}"
+	log_info "Done. Finished paching."
 }
 
 flash_boot() { # 刷入boot镜像
-	if [[ "${OS}" != "linux" ]]; then
-		echo "${BLUE}I: Flashing boot image...${RESET}"
+	if [[ "${OS}" == "android" ]]; then
+		log_info "Flashing boot image..."
 		if [[ -n "${TBOOTSUFFIX}" ]]; then
-			echo "${BLUE}I: You previously specified that you want to install to another slot. Target slot:${TBOOTSUFFIX}."
+			log_warn "You previously specified that you want to install to another slot. Target slot:${TBOOTSUFFIX}."
 			BOOTSUFFIX=${TBOOTSUFFIX}
 		fi
 		dd if=${WORKDIR}/new-boot.img of=${BYNAMEPATH}/boot${BOOTSUFFIX}
 		EXITSTATUS=$?
 		if [[ ${EXITSTATUS} != 0 ]]; then
-			echo "${RED}E: WARNING!!! IMAGE FLASH FAILED${RESET}"
-			echo "${YELLOW}I: Now trying to restore...${RESET}"
+			log_err "WARNING! IMAGE FLASH FAILED!"
+			log_err "Now trying to restore..."
 			dd if=${WORKDIR}/boot${BOOTSUFFIX}.img of=${BYNAMEPATH}/boot${BOOTSUFFIX}
 			EXITSTATUS=$?
 			if [[ ${EXITSTATUS} != 0 ]]; then
-				echo "${RED}E: WARNING!!! RESTORE FAILED!!!"
-				echo "Even I can't help you now. You can try to restore boot manually.${RESET}"
+				log_err "WARNING!!! RESTORE FAILED!!!"
+				log_err "Even I can't help you now. You can try to restore boot manually."
 				exit 1
 			fi
-			echo "${YELLOW}I: Restore Sucessfully.${RESET}"
+			log_info "Restore Sucessfully."
 		fi
-		echo "${GREEN}I: Flash done.${RESET}"
-		echo "${BLUE}I: Cleaning temporary files...${RESET}"
+		log_info "Flash done."
+		log_info "Cleaning temporary files..."
 		rm -rf ${WORKDIR}
-		echo "${GREEN}I: Done.${RESET}"
+		log_info "Done."
 	else
-		echo "${RED}E: You are trying to change this script. Linux does not require a flashing step. This is the second level of warning.${RESET}"
+		log_err "You are trying to change this script. Linux does not require a flashing step. This is the second level of warning."
+		exit 1
 	fi
 }
 
